name: Run project test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python 3.11.10
    - name: Set up Python 3.11.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./project

    - name: Make test.sh executable
      run: chmod +x test.sh
      working-directory: ./project

    - name: Run tests
      run: ./test.sh
      working-directory: ./project
